### ISSUE TITLE
[wallet adapter] support different transaction types

### ISSUE THREAD

**Issue by 0xmaayan** [aptos-labs/aptos-wallet-adapter#107]

**Comment by 0xbe1** [comment]
@0xmaayan I don't have context about this issue, however, I am looking to something like `signAndSubmitBCSTransaction` so that instead of passing in this txn payload:

```
declare type EntryFunctionPayload = {
    function: EntryFunctionId;
    /**
     * Type arguments of the function
     */
    type_arguments: Array<MoveType>;
    /**
     * Arguments of the function
     */
    arguments: Array<any>;
};
```

I can pass in something more detailed (compared to generic) payload like this:

```
declare type EntryFunctionPayload = {
    function: EntryFunctionId;
    /**
     * Type arguments of the function
     */
    type_arguments: Array<MoveType>;
    /**
     * Arguments of the function
     */
    arguments: Array<BCS.Bytes>;
};
```

So that I have complete control over how arguments are serialized using BCS. This is helpful for the "Write Contract" feature that I am currently working with Jill and Zihan in aptos explorer.

Do you mind providing more info? Ty!

**Comment by 0xmaayan** [comment]
@0xbe1 Hi, once https://github.com/aptos-labs/aptos-wallet-adapter/pull/108 lands, we would need to make sure wallets update their plugin on their side and then you would be able to submit bcs payload txns. Thanks!
